# Generated by Django 4.2.7 on 2024-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldb',
            name='timezone',
            field=models.CharField(blank=True, null=True, verbose_name='Часовой пояс'),
        ),
    ]
