# Generated by Django 4.2.7 on 2024-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_schooldb_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldb',
            name='timezone',
            field=models.CharField(verbose_name='Часовой пояс'),
        ),
    ]
