# Generated by Django 4.2.7 on 2024-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_schooldb_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldb',
            name='timezone',
            field=models.CharField(choices=[('+00:00', 'UTC'), ('+01:00', 'UTC+1'), ('+02:00', 'UTC+2'), ('+03:00', 'UTC+3'), ('+04:00', 'UTC+4'), ('+05:00', 'UTC+5'), ('+06:00', 'UTC+6'), ('+07:00', 'UTC+7'), ('+08:00', 'UTC+8'), ('+09:00', 'UTC+9'), ('+10:00', 'UTC+10'), ('+11:00', 'UTC+11'), ('+12:00', 'UTC+12')], verbose_name='Часовой пояс'),
        ),
    ]
