# Generated by Django 4.2.7 on 2024-04-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
