# Generated by Django 4.2.7 on 2024-04-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
