# Generated by Django 4.2.7 on 2024-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_alter_schedule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelesson',
            name='lesson10_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец урока 10'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson10_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало урока 10'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson1_end',
            field=models.TimeField(verbose_name='Конец урока 1'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson1_start',
            field=models.TimeField(verbose_name='Начало урока 1'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson2_end',
            field=models.TimeField(verbose_name='Конец урока 2'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson2_start',
            field=models.TimeField(verbose_name='Начало урока 2'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson3_end',
            field=models.TimeField(verbose_name='Конец урока 3'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson3_start',
            field=models.TimeField(verbose_name='Начало урока 3'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson4_end',
            field=models.TimeField(verbose_name='Конец урока 4'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson4_start',
            field=models.TimeField(verbose_name='Начало урока 4'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson5_end',
            field=models.TimeField(verbose_name='Конец урока 5'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson5_start',
            field=models.TimeField(verbose_name='Начало урока 5'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson6_end',
            field=models.TimeField(verbose_name='Конец урока 6'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson6_start',
            field=models.TimeField(verbose_name='Начало урока 6'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson7_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец урока 7'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson7_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало урока 7'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson8_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец урока 8'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson8_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало урока 8'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson9_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец урока 9'),
        ),
        migrations.AlterField(
            model_name='timelesson',
            name='lesson9_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало урока 9'),
        ),
    ]
