# Generated by Django 4.2.7 on 2024-04-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('schedules', '0011_studentclass_groupclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupClass',
            new_name='StudentGroup',
        ),
    ]
